runmode: test                 # 开发模式, debug, release, test 部署时环境变量覆盖
addr: :8080                  # HTTP绑定端口
name: food_service             # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  writers: file,stdout # 部署时输出到 stdout
  logger_level: DEBUG
  logger_file: log/food_server.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:  # DB 配置 部署时环境变量覆盖
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> c0210d5... update
  name: FOODSERVICE_DB_NAME
  addr: FOODSERVICE_DB_ADDR
  username: FOODSERVICE_DB_USERNAME
  password: FOODSERVICE_DB_PASSWORD
<<<<<<< HEAD
=======
=======
  name: food_service
  addr: 127.0.0.1
  username: root
  password:
>>>>>>> 0e703c7... update
>>>>>>> c0210d5... update
redis:  # redis 配置
  network: tcp
  max_num: 8
  addr: 127.0.0.1:6379